import Head from 'next/head'
import HomeFrutas from '../components/Entidades/Frutas/Index'



export default function Home() {
  return (
    <>
      <Head>
        <title>Tabela</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeFrutas/>
    </>
  )
}
